In [1]:
# Creating An Array And Performing Addition Of Two Matrices Using list And NumPy Array 

import numpy as np
A = np.array([[2,8],[6,3]])
B = np.array([[4,6],[7,9]])
Result = A + B
print("Array A:\n",A)
print("\nArray B:\n",B)
print("\n Addition of A and B:\n",Result)

Array A:
 [[2 8]
 [6 3]]

Array B:
 [[4 6]
 [7 9]]

 Addition of A and B:
 [[ 6 14]
 [13 12]]
